/** @type {const} */
export const SITE = {
  baseUrl: process.env.SITE_BASE_URL || 'https://www.fthenos.work',

  /**
   * Both apex and www URLs for sitemap entries (same paths on each origin).
   */
  getSitemapOrigins: () => {
    const primary = SITE.baseUrl.replace(/\/$/, '')
    const origins = new Set([primary])
    const m = primary.match(/^(https?:\/\/)(www\.)?(.+)$/i)
    if (m) {
      const [, proto, www, host] = m
      if (www) origins.add(`${proto}${host}`)
      else origins.add(`${proto}www.${host}`)
    }
    return [...origins]
  },
  author: {
    name: 'Lefteris Fthenos',
    bio: {
      en: 'Full stack developer and analytics lead — shipping Django, FastAPI, and Power BI solutions for teams worldwide.',
      el: 'Full stack developer και analytics lead — παραδίδω λύσεις Django, FastAPI και Power BI για ομάδες παγκοσμίως.',
    },
    image: '/public/og-image.png',
    links: {
      github: 'https://github.com/Lefyd24',
      linkedin: 'https://www.linkedin.com/in/eleftherios-fthenos',
      email: 'mailto:fthenosyd@gmail.com',
    },
  },
  ui: {
    en: {
      skip: 'Skip to content',
      scrollAria: 'Feed entry layout',
      navLabel: 'Primary navigation',
      navFeed: 'Feed',
      navOverview: 'Overview',
      navAbout: 'About',
      navWork: 'Work',
      navExperience: 'Experience',
      navSkills: 'Skills',
      navContact: 'Contact',
      langLabel: 'Select language',
      langCurrent: 'English',
      langEl: 'Ελληνικά',
      themeToggle: 'Toggle dark mode',
      openMenu: 'Open navigation menu',
      menuAria: 'Navigation links',
      themeMenu: 'Theme',
      breadcrumbHome: 'Home',
      breadcrumbFeed: 'Feed',
      relatedTitle: 'Related posts',
      tagsTitle: 'Tags',
      shareTitle: 'Share',
      readTime: (n) => `${n} min read`,
      published: 'Published',
      updated: 'Updated',
      featuredBadge: 'Featured',
      listTitle: 'Feed',
      listSubtitle: 'My personal repository of ideas, articles and notes.',
      listFeatured: 'Featured',
      listAll: 'All posts',
      tagPostsTagged: (tag) => `Posts tagged “${tag}”`,
      feedEmpty: 'Nothing in the feed yet.',
      tagPageEmpty: 'No posts with this tag.',
      allTags: 'All tags',
      footerRights: 'All rights reserved',
      twitterShare: 'Share on X',
      linkedinShare: 'Share on LinkedIn',
      facebookShare: 'Share on Facebook',
      redditShare: 'Share on Reddit',
      hackerNewsShare: 'Submit on Hacker News',
      blueskyShare: 'Share on Bluesky',
      telegramShare: 'Share on Telegram',
      whatsAppShare: 'Share on WhatsApp',
      emailShare: 'Share by email',
      copyLinkShare: 'Copy link',
      copyLinkDone: 'Copied',
    },
    el: {
      skip: 'Μετάβαση στο περιεχόμενο',
      scrollAria: 'Διάταξη καταχώρησης ροής',
      navLabel: 'Κύρια πλοήγηση',
      navFeed: 'Ροή',
      navOverview: 'Επισκόπηση',
      navAbout: 'Σχετικά',
      navWork: 'Έργα',
      navExperience: 'Εμπειρία',
      navSkills: 'Δεξιότητες',
      navContact: 'Επικοινωνία',
      langLabel: 'Επιλογή γλώσσας',
      langCurrent: 'Ελληνικά',
      langEn: 'English',
      themeToggle: 'Εναλλαγή θέματος',
      openMenu: 'Άνοιγμα μενού πλοήγησης',
      menuAria: 'Σύνδεσμοι πλοήγησης',
      themeMenu: 'Θέμα',
      breadcrumbHome: 'Αρχική',
      breadcrumbFeed: 'Ροή',
      relatedTitle: 'Σχετικές δημοσιεύσεις',
      tagsTitle: 'Ετικέτες',
      shareTitle: 'Κοινοποίηση',
      readTime: (n) => `${n} λεπτά ανάγνωσης`,
      published: 'Δημοσίευση',
      updated: 'Ενημέρωση',
      featuredBadge: 'Featured',
      listTitle: 'Ροή',
      listSubtitle: 'Το προσωπικό μου αποθετήριο ιδεών, άρθρων και σημειώσεων.',
      listFeatured: 'Featured',
      listAll: 'Όλες οι δημοσιεύσεις',
      tagPostsTagged: (tag) => `Δημοσιεύσεις με ετικέτα «${tag}»`,
      feedEmpty: 'Η ροή είναι ακόμη άδεια.',
      tagPageEmpty: 'Καμία δημοσίευση με αυτή την ετικέτα.',
      allTags: 'Όλες οι ετικέτες',
      footerRights: 'Με επιφύλαξη παντός δικαιώματος',
      twitterShare: 'Κοινοποίηση στο X',
      linkedinShare: 'Κοινοποίηση στο LinkedIn',
      facebookShare: 'Κοινοποίηση στο Facebook',
      redditShare: 'Κοινοποίηση στο Reddit',
      hackerNewsShare: 'Υποβολή στο Hacker News',
      blueskyShare: 'Κοινοποίηση στο Bluesky',
      telegramShare: 'Κοινοποίηση στο Telegram',
      whatsAppShare: 'Κοινοποίηση στο WhatsApp',
      emailShare: 'Κοινοποίηση με email',
      copyLinkShare: 'Αντιγραφή συνδέσμου',
      copyLinkDone: 'Αντιγράφηκε',
    },
  },
}
